app/users/forms.py
# /app/users/forms.py

from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, EqualTo, Length

class RegisterForm(Form):
    name = TextField('Username', validators=[DataRequired(), Length(min=6, max=25)])
    email = TextField('Email', validators=[DataRequired(), Length(min=6, max=254)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=10, max=40)])
    confirm = PasswordField('Repeat Password',[DataRequired(), EqualTo('password', message='Password must match')])
    
class LoginForm(Form):
    name = TextField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])

app/users/__init__.py
#__init.py__

app/users/views.py
# /app/users/views.py

from app import db
from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from app.views import login_required, flash_errors
from forms import RegisterForm, LoginForm
from app.models import User
from sqlalchemy.exc import IntegrityError

mod = Blueprint('users', __name__, url_prefix='/users',
                template_folder='templates', static_folder='static')

#logout
@mod.route('/logout/')
def logout():
    session.pop('logged_in', None)
    session.pop('user_id', None)
    flash('You are logged out.')
    return redirect(url_for('.login'))

#login  
@mod.route('/', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        u = User.query.filter_by(name=request.form['name'],
                                password=request.form['password']).first()
        if u is None:
            error = 'Invalid username or password.'
        else:
            session['logged_in'] = True
            session['user_id'] = u.id
            flash('You are logged in.  Go crazy.')
            return redirect(url_for('tasks.tasks'))
        
    return render_template('users/login.html',
                           form = LoginForm(request.form),
                           error=error)

# register
@mod.route('/register/', methods=['GET','POST'])
def register():
    error = None
    form = RegisterForm(request.form, csrf_enabled=False)
    if form.validate_on_submit():
        new_user = User(
            form.name.data,
            form.email.data,
            form.password.data,
            )
        try:
            db.session.add(new_user)
            db.session.commit()
            flash('Thanks for registering. Please login.')
            return redirect(url_for('.login'))
        except IntegrityError:
            error = "User and/or email already exists."
    else:
        flash_errors(form)
    return render_template('/users/register.html', form=form, error=error)
    

app/users/templates/users/login.html
<!-- /app/users/templates/users/login.html -->

{% extends "template.html" %}
{% block content %}
    <h1>Welcome to FlaskTaskr.</h1>
    <form class="form-signin" role="form" method="post" action="">
        <div class="lead">Please login to access your task list</div>
        {{ form.name.label }}: {{ form.name }}&nbsp;&nbsp;{{ form.password.label }}: {{ form.password }}&nbsp;&nbsp;
        <button class="btn btn-lg btn-primary" type="submit">Sign In</button>
        <br>
        <br>
        <p><em>Need an account?</em><a href="{{ url_for('users.register') }}"> Signup!!</a></p>
    </form>
{% endblock %}

app/users/templates/users/register.html
<!-- /app/users/templates/users/register.html -->
{% extends 'template.html' %}
{% block content %}
    <h1>Welcome to FlaskTaskr</h1>
        <form class="form-signin" role="form" method="POST" action="">
            <div class="lead">Please register to start your task list</div>
            <p>{{ form.name.label }}: {{ form.name }} &nbsp;&nbsp;{{ form.email.label }}: {{ form.email }}</p>
            <p>{{ form.password.label }}: {{ form.password }}&nbsp;&nbsp;{{ form.confirm.label }}: {{ form.confirm }}</p>
            <button class="btn btn-lg btn-primary" type="submit">Register</button>
            <br>
            <br>
            <p><em>Already registered?</em> Click <a href="{{ url_for('users.login') }}">here</a> to login.</p>
        </form>
{% endblock %}

app/users/templates/users/template.html
<!-- add a template specific to the users component (if desired) -->