app/tasks/forms.py
# /app/tasks/forms.py

from flask_wtf import Form
from wtforms import TextField, DateField, IntegerField, SelectField
from wtforms.validators import DataRequired

class AddTask(Form):
    task_id = IntegerField('Priority')
    name = TextField('Task Name', validators=[DataRequired()])
    due_date = DateField('Due Date (mm/dd/yyyy)',
                         validators=[DataRequired()], format='%m/%d/%Y')
    priority = SelectField('Priority', validators=[DataRequired()],
                           choices=[('1','1'), ('2','2'), ('3','3'), ('4','4'),
                                    ('5','5')])
    status = IntegerField('Status')
    posted_date = DateField('Posted date (mm/dd/yyyy)',
                            validators=[DataRequired()], format="%m/%d/%Y")

app/tasks/__init__.py
#__init.py__

app/tasks/views.py
# /app/tasks/views.py

from app import db
from flask import (Blueprint, flash, redirect, render_template,
                   request, session, url_for)
from app.views import login_required, flash_errors
from forms import AddTask
from app.models import FTasks

mod = Blueprint('tasks', __name__, url_prefix='/tasks',
                template_folder='templates', static_folder='static')

@mod.route('/tasks/')
@login_required
def tasks():
    open_tasks = db.session.query(FTasks).filter_by(status='1').order_by(
                    FTasks.due_date.asc())
    closed_tasks = db.session.query(FTasks).filter_by(status='0').order_by(
                    FTasks.due_date.asc())
    return render_template('tasks/tasks.html', form = AddTask(request.form),
                           open_tasks=open_tasks, closed_tasks=closed_tasks)

#add new tasks
@mod.route('/add/', methods=["GET", "POST"])
@login_required
def new_task():
    form = AddTask(request.form, csrf_enabled=False)
    if form.validate_on_submit():
        new_task = FTasks(
            form.name.data,
            form.due_date.data,
            form.priority.data,
            form.posted_date.data,
            '1',
            session['user_id']
            )
        db.session.add(new_task)
        db.session.commit()
        flash("New entry was successfuly posted.  Thank you.")
    else:
        flash_errors(form)
    return redirect(url_for('.tasks'))

# mark tasks as complete
@mod.route('/complete/<int:task_id>/',)
@login_required
def complete(task_id):
    new_id = task_id
    db.session.query(FTasks).filter_by(task_id=new_id).update({"status":"0"})
    db.session.commit()
    flash('The task was marked as complete.')
    return redirect(url_for('.tasks'))

# delete tasks
@mod.route('/delete/<int:task_id>/',)
@login_required
def delete_entry(task_id):
    new_id = task_id
    db.session.query(FTasks).filter_by(task_id=new_id).delete()
    db.session.commit()
    flash('The task was deleted.')
    return redirect(url_for('.tasks'))

app/tasks/templates/tasks/tasks.html
{% extends "template.html" %}
{% block content %}
<h1>Welcome to FlaskTaskr</h1>
<div class="add-task">
    <div class="lead">Add a new task:</div>
        <form action="{{ url_for('tasks.new_task') }}" method="post" role="form">
            <p>
                {{ form.name.label }}: {{ form.name }}<br>
                {{ form.due_date.label }}: {{form.due_date }}<br>
                {{ form.posted_date.label }}: {{ form.posted_date }}&nbsp;{{ form.priority.label }}: {{ form.priority }}
                <button class="btn btn-md btn-primary" type="submit">Submit</button></p>
        </form>
</div>
<div class="entries">
    <br>
    <br>
    <div class="lead">Open Tasks:</div>
    <br>
    <table class = "table table-bordered">
        <thead>
            <tr>
                <th>Task Name</th>
                <th>Due Date</th>
                <th>Posted Date</th>
                <th>Priority</th>
                <th>Posted By</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for o in open_tasks %}
                <tr>
                    <td>{{ o.name }}</td>
                    <td>{{ o.due_date }}</td>
                    <td>{{ o.posted_date }}</td>
                    <td>{{ o.priority }}</td>
                    <td>{{ o.poster.name }}</td>
                    <td>
                        <a href="{{ url_for('tasks.delete_entry', task_id = o.task_id) }}">Delete</a> -
                        <a href="{{ url_for('tasks.complete', task_id = o.task_id) }}">Mark as complete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<br>
<br>
<div class="entries">
    <div class="lead">Closed Tasks:</div>
    <br>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Task Name</th>
                <th>Due Date</th>
                <th>Posted Date</th>
                <th>Priority</th>
                <th>Posted By</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for c in closed_tasks %}
                <tr>
                    <td>{{ c.name }}</td>
                    <td>{{ c.due_date }}</td>
                    <td>{{ c.posted_date }}</td>
                    <td>{{ c.priority }}</td>
                    <td>{{ c.poster.name }}</td>
                    <td>
                        <a href="{{ url_for('tasks.delete_entry', task_id = c.task_id) }}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}