app/users/views.py
# /app/users/views.py

from app import db
from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from app.views import login_required, flash_errors
from forms import RegisterForm, LoginForm
from app.models import User
from sqlalchemy.exc import IntegrityError

mod = Blueprint('users', __name__, url_prefix='/users',
                template_folder='templates', static_folder='static')

#logout
@mod.route('/logout/')
def logout():
    session.pop('logged_in', None)
    session.pop('user_id', None)
    flash('You are logged out.')
    return redirect(url_for('.login'))

#login  
@mod.route('/', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        u = User.query.filter_by(name=request.form['name'],
                                password=request.form['password']).first()
        if u is None:
            error = 'Invalid username or password.'
        else:
            session['logged_in'] = True
            session['user_id'] = u.id
            flash('You are logged in.  Go crazy.')
            return redirect(url_for('tasks.tasks'))
        
    return render_template('users/login.html',
                           form = LoginForm(request.form),
                           error=error)

# register
@mod.route('/register/', methods=['GET','POST'])
def register():
    error = None
    form = RegisterForm(request.form, csrf_enabled=False)
    if form.validate_on_submit():
        new_user = User(
            form.name.data,
            form.email.data,
            form.password.data,
            )
        try:
            db.session.add(new_user)
            db.session.commit()
            flash('Thanks for registering. Please login.')
            return redirect(url_for('.login'))
        except IntegrityError:
            error = "User and/or email already exists."
    else:
        flash_errors(form)
    return render_template('/users/register.html', form=form, error=error)
    

app/templates/register.html
{% extends 'template.html' %}
{% block content %}
    <h1>Welcome to FlaskTaskr</h1>
        <form class="form-signin" role="form" method="POST" action="">
            <div class="lead">Please register to start your task list</div>
            <p>{{ form.name.label }}: {{ form.name }} &nbsp;&nbsp;{{ form.email.label }}: {{ form.email }}</p>
            <p>{{ form.password.label }}: {{ form.password }}&nbsp;&nbsp;{{ form.confirm.label }}: {{ form.confirm }}</p>
            <button class="btn btn-lg btn-primary" type="submit">Register</button>
            <br>
            <br>
            <p><em>Already registered?</em> Click <a href="/">here</a> to login.</p>
        </form>
{% endblock %}

app/templates/template.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <Title>Welcome to FlaskTaskr</Title>
        <!-- STYLES -->
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename="css/styles.css") }}">
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">FlaskTaskr</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        {% if not session.logged_in %}
                            <li><a href="{{url_for('users.register')}}">Signup</a></li>
                        {% else %}
                            <li><a href="{{url_for('users.logout')}}">Logout</a></li>
                        {% endif %}
                    </ul>
                </div><!-- /.navbar-collapse-->
            </div>
        </div>
        <div class="container">
            <div class="content">
                {% for message in get_flashed_messages() %}
                    <div class="flash">{{ message }}</div>
                    <br/>
                {% endfor %}
                {% if error %}
                    <div class="error"><strong>Error:</strong>{{ error }}</div>
                {% endif %}
                {% block content %}
                {% endblock %}
            </div>
            <div class="footer">
                <hr>
                <p>&copy; 20-something</p>
            </div>
        </div><!--/.container-->
        <!-- Scripts -->
        <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    </body>
</html>